apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ./welcome.yaml
patchesJson6902:
  - target:
      version: v1
      group: apps
      kind: Deployment
      name: welcome-php
    patch: |-
      - op: add
        path: /metadata/labels/testkey
        value: testvalue
